### ISSUE TITLE
The model architecture may different from paper.

### ISSUE THREAD

**Issue by songdoyouho** [sercant/mobile-segmentation#14]
Hi, @sercant !

Thank you for sharing this fantastic project!

I found that in core/shufflenet_v2.py line 69 "layer_stride = 1" will cause the parameter "rate" as 1 instead of 2 in shufflenet V2 stage 4.

Could you check this small issue?

Thanks

**Comment by sercant** [comment]
Hello @songdoyouho,

Thank you for your interest. Yes, in fact, you are correct. One other person also pointed out the error to me via email. I didn't fix it since the checkpoints use the code as it is. In the meantime, I am training the network again with the correct stride adjustment. The new checkpoints might be available later on when I finish experimenting. The person pointed out the mistake also said that they tried the network with the correct stride and it didn't contribute to the accuracy. (But, the error causes the network to underperform if the output stride value is lowered. i.e. 8 while it should increase the accuracy)

**Comment by songdoyouho** [comment]
Thank you for your instant reply!

Wish you have a nice year.
