### ISSUE TITLE
Run code on the mobile

### ISSUE THREAD

**Issue by InstantWindy** [sercant/mobile-segmentation#5]
Hi! I‘m really interested in your paper. Do you plan to implement the code in pytorch?  How to run the code on the mobile platform? Thanks!

**Comment by sercant** [comment]
Hi @InstantWindy, thank you for your interest. There is no plan to implement the code in pytorch at the moment but a re-write using the new tensorflow API might happen. Since tensorflow is easy to be exported for mobile targets such as smartphones using tf-lite, it was the choice of framework. I am not sure if pytorch runs on Android or iOS.

To run on the network on a mobile platform one should export the trained model to tf-lite using the `export_tflite.py`. After that, you can see a simple Android application that I have implemented at this repository: [sercant/android-segmentation-app][1].

[1]: https://github.com/sercant/android-segmentation-app

**Comment by InstantWindy** [comment]
Thanks for your reply.  How do you implement DPC(dense predictioncell ) ?

**Comment by sercant** [comment]
I'm not quite sure what did you mean by how do I implement DPC but it is a part of the network so the exported model already contains the architecture. The architecture of the module is described in the paper and also here in the repository you can see the `core/dense_prediction_cell_branch5_top1_cityscapes.json` file and `model.py` for the implementation.

**Comment by InstantWindy** [comment]
I mean how you get the DPC module . How do you get the parameters of file "dense_prediction_cell_branch5_top1_cityscapes.json" . Thanks!

**Comment by sercant** [comment]
The parameters of the DPC module was found in [*Searching for Efficient Multi-Scale Architectures for Dense Image Prediction*][1] by LC Chen. The code that parses the JSON file is under the `core` folder. Let me know if this answers your question and don't hesitate to ask more if you have any.

[1]: http://papers.nips.cc/paper/8087-searching-for-efficient-multi-scale-architectures-for-dense-image-prediction
