### ISSUE TITLE
Some things about MS COCO 2017

### ISSUE THREAD

**Issue by lilingge** [sercant/mobile-segmentation#7]
Hi author，I see that you have used COCO 2017 data set for network pre-training processing.
I  implemente a semantic segmentation network and download the COCO 2017 data set. I want to know how to get the label images(grey images) from the annotations'json.

**Comment by sercant** [comment]
Hello @lilingge,

The code for preparing the COCO dataset is under `dataset` folder. In particular, you can examine the `dataset/download_and_convert_ms_coco.sh` and `dataset/build_coco_data.py`. This repository uses `.tfrecord` format for the data. But if you want the label PNGs you can change the code a little bit.

See this line here:

https://github.com/sercant/mobile-segmentation/blob/9cac777740fd55ef67099611aee720f44774264c/dataset/build_coco_data.py#L160-L162

Instead of saving it to `BytesIO` you can give an output file path. Documentation related to PIL is [here][1].

[1]: https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save

**Comment by lilingge** [comment]
> Hello @lilingge,
> 
> The code for preparing the COCO dataset is under `dataset` folder. In particular, you can examine the `dataset/download_and_convert_ms_coco.sh` and `dataset/build_coco_data.py`. This repository uses `.tfrecord` format for the data. But if you want the label PNGs you can change the code a little bit.
> 
> See this line here:
> 
> https://github.com/sercant/mobile-segmentation/blob/9cac777740fd55ef67099611aee720f44774264c/dataset/build_coco_data.py#L160-L162
> 
> Instead of saving it to `BytesIO` you can give an output file path. Documentation related to PIL is [here](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save).

There is something wrong in build_data.py
 python3 build_coco_data.py --dataset_dir ./COCO/ --output_dir ./COCO/tfrecord --category_names person,car,truck,bus,train,motorcycle,bicycle,stop\ sign,parking\ meter --min_pixels 1000;
Traceback (most recent call last):
  File "build_coco_data.py", line 11, in <module>
    import build_data
  File "/data1/llg/Documents/build_data.py", line 23, in <module>
    tf.app.flags.DEFINE_enum('image_format', 'png', ['jpg', 'jpeg', 'png'],
AttributeError: module 'tensorflow.python.platform.flags' has no attribute 'DEFINE_enum'

**Comment by sercant** [comment]
Dear @lilingge,

It's just an error related to the flags. Please search this kind of Tensorflow related errors. It might be because your Tensorflow version is old.

**Comment by lilingge** [comment]
> Dear @lilingge,
> 
> It's just an error related to the flags. Please search this kind of Tensorflow related errors. It might be because your Tensorflow version is old.

TypeError: u'./COCO//val2017/000000397133.jpg' has type unicode, but expected one of: bytes
