### ISSUE TITLE
Three questions about DPC module

### ISSUE THREAD

**Issue by lilingge** [sercant/mobile-segmentation#9]
Hi,author.Your proposed network is very interesting and effective！
The first questions, the DPC encoder head have 5 franches. 
Every franches have 256 channels, then we can get 1280 channels by concat, but in Table 1, 
the DPC module's Output Channels are 512. Why?
The second, the rates in DPC is interesting, why are 1X6, 18X15, 6X3, 6X21?I see the deeplabv3+'s rate are 6, 12 ,18. 
The last, the each franch in DPC troubles me.I can't understand the reasons.

I'm sorry for asking so many questions, I have an additional question. Why you preprocess the input images by standardizing each pixel to [-1, 1] rather than [0, 1] or not do this operation?

**Comment by sercant** [comment]
Hello @lilingge,

1. Thank you for pointing out that the output channel number in Table 1 is mismatching. I have noticed that 512 is, in fact, wrong and belongs to the "basic" head. The DPC head has 1280 output channels.
2. The DPC encoder head is found in this paper: [*Searching for Efficient Multi-Scale Architectures for Dense Image Prediction*][1]. The module is a result of a random search and is shown to be better than DeeplabV3+'s `6, 12, 18` for Cityscapes dataset in the linked paper. Since it is not hand-crafted, it is harder to explain why `1x6, 18x15, 6x3, 6x21` works better.
3. The standardization to `[-1, 1]` range is a choice and but the aim is to basically have the mean value at 0. If you see the ImageNet papers you might notice that, commonly, a similar approach is taken by subtracting the mean and dividing the result by the standard deviation. This is to get the input to follow a gaussian distribution centered around point 0. Standardizing to `[-1, 1]` is said to work better with `ReLU(0, x)` non-linearity function (which is used in this work). But you shouldn't focus much on the normalization function as I think, it doesn't have much importance.

Hope I was able to answer your questions and please don't hesitate to ask more. Thank you for pointing out the error in Table 1.

[1]: https://arxiv.org/abs/1809.04184

**Comment by zyh990211** [comment]
Hello, author! I am studying your code and have some problems I can't understand.
1. In the shufflenet_v2.py, function shufflenet_base, output_stride=32 and
```
layers = [
            {'num_units': 4, 'out_channels': initial_depth,
                'scope': 'Stage2', 'stride': 2},
            {'num_units': 8, 'out_channels': None,
                'scope': 'Stage3', 'stride': 2},
            {'num_units': 4, 'out_channels': None,
                'scope': 'Stage4', 'stride': 2},
        ]
```
But in the Table1, the stride of Stage4 is 1 and the output_stride=16. I can't understand.
2. In the feature_extractor.py,
```
# Mean pixel value.
_MEAN_RGB = [123.15, 115.90, 103.06]
```
I don't know where the three numbers come from.
Thank you very much!!

**Comment by sercant** [comment]
Hello zyh990211,

Thank you for your interest in the paper. I will try to explain as best as I can:

1. The output_stride of the original shufflenet_v2 is 32 but in the network this value comes from the parameter. If you notice the function definition:
def shufflenet_base(input_tensor,
                    depth_multiplier=1.0,
                    scope='ShuffleNetV2',
                    is_training=False,
                    output_stride=None,
                    **kwargs):

This value is set by the flags through the train.py, evaluate.py etc. and then carried over to the feature_extractor.py which calls the function with the desired output_stride value. This value is default in the train.py as shown here:
flags.DEFINE_integer('output_stride', 16, 'The ratio of input to output spatial resolution.')

The layer definition that you have sent is the original shufflenet_v2 layer structure. If you pay attention to the get_stride function, instead of increasing the downsampling factor in each downsampling layer, if a stage will lower the total downsampling factor higher than the (output_stride) than we increase the rate of the convolutions instead. Maybe the image in the attachment may give you a better understanding.

2. Those values are not used. Images are preprocessed using _preprocess_zero_mean_unit_range function.

I suggest you to use a debugger to follow the code, that way you can see better about whats going on. Let me know if you have more questions.

Best regards,
Sercan Turkmen.

[cid:A7DBF1E9-98D2-4FC6-A411-3E364F7BEC79@oulu.fi]

On 17 Jul 2019, at 17.23, zyh990211 <notifications@github.com<mailto:notifications@github.com>> wrote:

output_stride

**Comment by zyh990211** [comment]
Hello Sercan Turkmen,


Thank you for the explaination that is so clear and easy to understand. I have understood this part of code.
I am a sophomore in China. My skills and experience are insufficient. Your suggestion is very helpful.
Thank you very much!!


Best wishes,
Yuhang Zhu




------------------ 原始邮件 ------------------
发件人: "Sercan Turkmen"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 晚上10:49
收件人: "sercant/mobile-segmentation"<mobile-segmentation@noreply.github.com>;
抄送: "zhu"<547637252@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [sercant/mobile-segmentation] Three questions about DPC module(#9)



Hello zyh990211,
 
 Thank you for your interest in the paper. I will try to explain as best as I can:
 
 1. The output_stride of the original shufflenet_v2 is 32 but in the network this value comes from the parameter. If you notice the function definition:
 def shufflenet_base(input_tensor,
                     depth_multiplier=1.0,
                     scope='ShuffleNetV2',
                     is_training=False,
                     output_stride=None,
                     **kwargs):
 
 This value is set by the flags through the train.py, evaluate.py etc. and then carried over to the feature_extractor.py which calls the function with the desired output_stride value. This value is default in the train.py as shown here:
 flags.DEFINE_integer('output_stride', 16, 'The ratio of input to output spatial resolution.')
 
 The layer definition that you have sent is the original shufflenet_v2 layer structure. If you pay attention to the get_stride function, instead of increasing the downsampling factor in each downsampling layer, if a stage will lower the total downsampling factor higher than the (output_stride) than we increase the rate of the convolutions instead. Maybe the image in the attachment may give you a better understanding.
 
 2. Those values are not used. Images are preprocessed using _preprocess_zero_mean_unit_range function.
 
 I suggest you to use a debugger to follow the code, that way you can see better about whats going on. Let me know if you have more questions.
 
 Best regards,
 Sercan Turkmen.
 
 [cid:A7DBF1E9-98D2-4FC6-A411-3E364F7BEC79@oulu.fi]
 
 On 17 Jul 2019, at 17.23, zyh990211 <notifications@github.com<mailto:notifications@github.com>> wrote:
 
 output_stride

**Comment by sercant** [comment]
Happy that I was able to help. I hope you found the code and the network useful for your project.
